<div class="loadingio-spinner-pulse">
	<div class="ldio">
		<div />
		<div />
		<div />
		<div />
	</div>
</div>

<style type="text/css">
	@keyframes ldio-1 {
		0%,
		100% {
			top: 2em;
			height: 2em;
		}
		40% {
			top: 0em;
			height: 2em;
		}
		70% {
			top: 0.8em;
			height: 2em;
		}
	}
	@keyframes ldio-2 {
		0% {
			top: 2em;
			height: 2em;
		}
		30% {
			top: 0.8em;
			height: 2em;
		}
		100% {
			top: 0.3em;
			height: 2em;
		}
	}
	@keyframes ldio-3 {
		0% {
			top: 2em;
			height: 2em;
		}
		30% {
			top: 1em;
			height: 2em;
		}
		100% {
			top: 0.5em;
			height: 2em;
		}
	}
	@keyframes ldio-4 {
		0% {
			top: 2em;
			height: 2em;
		}
		30% {
			top: 1.2em;
			height: 2em;
		}
		100% {
			top: 0.8em;
			height: 2em;
		}
	}
	.ldio div {
		position: absolute;
		width: 2ch;
	}
	.ldio div:nth-child(1) {
		left: 1ch;
		background: #121618;
		animation: ldio-1 1s cubic-bezier(0, 0.5, 0.5, 1) infinite;
		animation-delay: -0.2s;
	}
	.ldio div:nth-child(2) {
		left: 3ch;
		background: #202d37;
		animation: ldio-2 1s cubic-bezier(0, 0.5, 0.5, 1) infinite;
		animation-delay: -0.1s;
	}
	.ldio div:nth-child(3) {
		left: 5ch;
		background: #2b3945;
		animation: ldio-3 1s cubic-bezier(0, 0.5, 0.5, 1) infinite;
		animation-delay: 0s;
	}
	.ldio div:nth-child(4) {
		left: 7ch;
		background: #c3c3c4;
		animation: ldio-4 1s cubic-bezier(0, 0.5, 0.5, 1) infinite;
		animation-delay: 0s;
	}

	.loadingio-spinner-pulse {
		width: 10ch;
		height: 1.5em;
		display: inline-block;
		overflow: hidden;
		background: #f1f2f3;
	}
	.ldio {
		width: 100%;
		height: 100%;
		position: relative;
		transform: translateZ(0) scale(1);
		backface-visibility: hidden;
		transform-origin: 0 0; /* see note above */
	}
	.ldio div {
		box-sizing: content-box;
	}
	/* generated by https://loading.io/ */
</style>
